/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AsideArea: typeof import('./src/components/SideBar/AsideArea.vue')['default']
    AssistantModal: typeof import('./src/components/AssistantChat/AssistantModal.vue')['default']
    Bubble: typeof import('./src/components/MessageBubble/Bubble.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderArea: typeof import('./src/components/Header/HeaderArea.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MessageArea: typeof import('./src/components/AssistantChat/MessageArea.vue')['default']
    MessageBubble: typeof import('./src/components/AssistantChat/MessageBubble.vue')['default']
    MessageInputbox: typeof import('./src/components/AssistantChat/MessageInputbox.vue')['default']
    MessageInputBox: typeof import('./src/components/AssistantChat/MessageInputBox.vue')['default']
    MessageUserBubble: typeof import('./src/components/AssistantChat/MessageUserBubble.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSplit: typeof import('naive-ui')['NSplit']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TChatActionbar: typeof import('@tdesign-vue-next/chat')['ChatActionbar']
    TChatContent: typeof import('@tdesign-vue-next/chat')['ChatContent']
    TChatInput: typeof import('@tdesign-vue-next/chat')['ChatInput']
    TChatList: typeof import('@tdesign-vue-next/chat')['ChatList']
    TChatMarkdown: typeof import('@tdesign-vue-next/chat')['ChatMarkdown']
    TChatMessage: typeof import('@tdesign-vue-next/chat')['ChatMessage']
    TChatSender: typeof import('@tdesign-vue-next/chat')['ChatSender']
    TSpace: typeof import('tdesign-vue')['Space']
  }
}
